exception false : {foo|bar|foo} -> with
